apiVersion: skaffold/v2alpha4
kind: Config
metadata:
  name: chachkie-server
build:
  local:
    push: true
  artifacts:
    - image: chachkie-server
      context: chachkie-server/
      jib: {}
    - image: chachkie-client
      context: chachkie-client/
      jib: {}      
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - knative/service-*.yaml