apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chachkie-server
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ashumilov/chachkie-server
        env:
        - name: TARGET
          value: "Chachkie Server v1"