apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: chachkie-client
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: ashumilov/chachkie-client
        env:
        - name: TARGET
          value: "Chachkie Client v1"
        - name: SPRING_PROFILES_ACTIVE
          value: knative  